version: '3.9'

services:
  api:
    build: .
    container_name: fastapi-ddd
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/todos.db
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  sqlite_data:
